// Auto-generated from SE 0.7.57 universe-raw.lua.

pub const Body = struct { name: []const u8, patron: ?[]const u8, primary_resource: ?[]const u8, has_biome_replacements: bool, has_tags: bool, };

pub const stars = [_][]const u8{
    "Calidus",
    "Astermore",
    "Statarius",
    "Nalara",
    "Errioni",
    "Kalmaia",
    "Merlime",
    "Halsian",
    "Cordova",
    "Alacrity",
    "Auriel",
    "Penthus",
    "Angelus",
    "Basilius",
    "Auphorus",
    "Pontus",
    "Sargus",
    "Rigelus",
    "Tanius",
    "Terebellus",
    "Capellus",
    "Hankorus",
    "Brunnus",
    "Vozanus",
    "Teamagus",
    "Wexovis",
    "Electra",
    "Sephi",
    "Assimius",
    "Argus",
    "Calamity",
};

pub const space_zones = [_][]const u8{
    "Asteroidia",
    "Astral Snow",
    "Breadcrumbs",
    "Broken Mirror",
    "Black Mirror",
    "Bumperfield",
    "Caltrops",
    "Crystal Collective",
    "Creepy Hollow",
    "Cosmic Dustlands",
    "Dark Assemblage",
    "Darkflare",
    "Deadspace",
    "Dusty Voids",
    "Ephemeral Expanse",
    "Felleim",
    "Galactic Gravel",
    "Godash",
    "Grapeshot",
    "Galactic Graveyard",
    "Haunted Hollows",
    "Hailstorm",
    "Interstellar Grotto",
    "Interstellar Barrens",
    "Ice Field",
    "Kaleidoscope",
    "Melancholia",
    "Oblongglobulata",
    "Poltergeist",
    "Pebbles",
    "Rocky Ridge",
    "Razor Field",
    "Realm of Shadows",
    "Sands of Time",
    "Shadeland",
    "Sea of Sorrows",
    "Shattered Skies",
    "Stardew",
    "Stardust",
    "Stone Circles",
    "Solar Entrails",
    "Slumberland",
    "Starcorpse",
    "Sky Fragments",
    "Specter",
};

pub const average_moons_per_planet: f64 = 3;
pub const max_asteroid_belts: u32 = 2;

pub const unassigned_planets = [_]Body{
    .{ .name="Arendel", .patron=null, .primary_resource="uranium-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Orchid", .patron=null, .primary_resource="copper-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Anathema", .patron=null, .primary_resource="iron-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Tigris", .patron=null, .primary_resource="stone", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Bellerophon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Theseus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Snek", .patron="Snek", .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Maelstrom", .patron=null, .primary_resource="iron-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Crystalys", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Nostos", .patron=null, .primary_resource="uranium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Raegis", .patron=null, .primary_resource="copper-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Poseidon", .patron=null, .primary_resource="crude-oil", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Wilde", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Zegul", .patron=null, .primary_resource="coal", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Charon", .patron=null, .primary_resource="copper-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Titan", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
};

pub const unassigned_moons = [_]Body{
    .{ .name="Feluna", .patron=null, .primary_resource="iron-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Segel", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Leto", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Mixin", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Albion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Husky", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Butterfly", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Bluna", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Auberge", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Harbistaz", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Minkey", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Pengwing", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Jackneevle", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Yetermoon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Alwego", .patron="Alwego", .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
};

pub const unassigned_planets_or_moons = [_]Body{
    .{ .name="Untra", .patron="Untra", .primary_resource="iron-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Nell", .patron="Cpp", .primary_resource="se-holmium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Sylvateu", .patron="Penitencia", .primary_resource="se-iridium-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Aurelios", .patron="Joshua Tibbetts", .primary_resource="se-vulcanite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Hellmouth", .patron="Stuart Whelan", .primary_resource="se-vulcanite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Matyus", .patron="jmatya", .primary_resource="se-vulcanite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Orbadon", .patron="Orbadon", .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Feist", .patron="Warren Rosenau", .primary_resource="se-vulcanite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Irinchik", .patron="Eduard Tyantov", .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Orsa", .patron="ppeellllee", .primary_resource="se-iridium-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Jibber", .patron="David Hillier", .primary_resource="se-iridium-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Lameuffen", .patron="Hazmodan", .primary_resource="copper-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Sapphire", .patron="Stephanie Miller", .primary_resource="se-beryllium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Yggdrasil", .patron="mishugashu", .primary_resource="se-vitamelange", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Cybros", .patron="FairEnough", .primary_resource="se-beryllium-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Tzelma", .patron="Scott McCoy", .primary_resource="se-holmium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Mina", .patron="PonSquared", .primary_resource="iron-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Greger", .patron="Anton Bergåker", .primary_resource="iron-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Murasaki", .patron="CaitSith2", .primary_resource="crude-oil", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Faustus", .patron="March McLaughlin", .primary_resource="se-cryonite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Tinfaya", .patron="Major Painpoint", .primary_resource="stone", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Melkor", .patron="Charles Vaughn", .primary_resource="se-iridium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Thurion", .patron="Koelbloed", .primary_resource="iron-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Jinxjazz", .patron="JinxAndJazz", .primary_resource="se-cryonite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Yuraq", .patron="frigidplanet", .primary_resource="se-cryonite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Braenora", .patron="DrAgniBraenor", .primary_resource="se-cryonite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Lozekam", .patron="xandkat", .primary_resource="se-cryonite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Boerdig", .patron="letsgo2u", .primary_resource="se-vulcanite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Goose", .patron="H. Goose", .primary_resource="se-iridium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Corrine", .patron="Shadowclaimer", .primary_resource="se-holmium-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Willownezz", .patron="Willownezz", .primary_resource="se-vulcanite", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Antsoutwelt", .patron="Reroll Jenkins", .primary_resource="se-vitamelange", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Grishord", .patron="Grishord", .primary_resource="se-vitamelange", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Derry", .patron="Derry", .primary_resource="crude-oil", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Seehusen", .patron="Sashalicious", .primary_resource="se-vulcanite", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Etreum", .patron="Valeria", .primary_resource="iron-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Sansara", .patron="Xsansara", .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Lizava", .patron="OneWheelDude", .primary_resource="se-beryllium-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Norfair", .patron="Syd", .primary_resource="se-holmium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Robbebol", .patron="TheCuriousClown", .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Snezon", .patron="PrismaticKevin", .primary_resource="se-holmium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Cinza", .patron="Ash2ruin", .primary_resource="se-vulcanite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Xorius", .patron="Xor", .primary_resource="se-holmium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Lacero", .patron="Lacero", .primary_resource="se-cryonite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Exallander", .patron="Boardoe", .primary_resource="se-iridium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Eris", .patron="NextToZero", .primary_resource="crude-oil", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Cetria", .patron="Pelf", .primary_resource="se-vitamelange", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Kraine", .patron="Дмитро Кравченко", .primary_resource="uranium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Porcyka", .patron="Lost Hamster", .primary_resource="se-iridium-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Cootiepuss", .patron="SMuffatti", .primary_resource="se-vitamelange", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Zirbs", .patron="Zirbs", .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Raven", .patron="Ravish", .primary_resource="crude-oil", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Xynariz", .patron="Xynariz", .primary_resource="kr-rare-metal-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Irilea", .patron="Iliurgul", .primary_resource="se-vitamelange", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Arcanis", .patron="KMack413", .primary_resource="crude-oil", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Lendiana", .patron="Polish Deathcare", .primary_resource="uranium-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Coniferous", .patron="Coniferous", .primary_resource="se-vitamelange", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Mirage", .patron="Shylo132", .primary_resource="iron-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Noveria", .patron="Luckay", .primary_resource="se-beryllium-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Vorlon", .patron="SirVorlon", .primary_resource="se-iridium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Marquardt", .patron="Andree", .primary_resource="stone", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Tarn", .patron="Tarn", .primary_resource="se-cryonite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Ketobar", .patron="Valanna", .primary_resource="se-iridium-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Horaerratum", .patron="slipsec", .primary_resource="se-vitamelange", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Katalos", .patron="PeterHan5", .primary_resource="se-beryllium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Drakkett", .patron="Drakkett", .primary_resource="se-cryonite", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Xiada", .patron="CrushedIce", .primary_resource="se-vitamelange", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Sparky", .patron="Sparky", .primary_resource="se-holmium-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Trelos", .patron="madman", .primary_resource="crude-oil", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Sandro", .patron="Sandro", .primary_resource="iron-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Neenuvar", .patron="Neenuvar", .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Kamsta", .patron="Kamsta", .primary_resource="iron-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Jasbury", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Atropos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Mormo", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Viken", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Katar", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Liko", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Plato", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Talos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Capritos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Yaegner", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Gigei", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Kujaku", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Aciszar", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Toxinora", .patron=null, .primary_resource="crude-oil", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Hestia", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Avorion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Mercutio", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Elolis", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Horkos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Riven", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Techne", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Bomore", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Prabhava", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Anemoi", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ismene", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Owleye", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Theia", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Isabella", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Thanatos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Nechrophos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Morpheus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Eleusis", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Nike", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Pollus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hadrian", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Meleager", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Sapperious", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Arkazious", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hyratel", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Atonoy", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Dafdee", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Bordoli", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Dinotress", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Helburn", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Horae", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hybris", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Fodius", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Petra", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Zafis", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Kerel", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Claustry", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Anson", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Reaver", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Arae", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Magaera", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Dagon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Glasties", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Phoebe", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Vestrian", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Rovecutio", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hexagee", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Unilix", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Eirene", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Rouk", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Rupel", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Dyton", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Miranda", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Aghanim", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Octarine", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Veden", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Mireska", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tarrasque", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Parth", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Jenova", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Lich", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Farangis", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Pelorum", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hera", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Vyse", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Argenta", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Rooftrellen", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Avez", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Theoden", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Nookryme", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Lyralei", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Agon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Eshone", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Rolium", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Exorrion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Sage", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Persophone", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hemera", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Shashi", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Skadi", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Geryon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Juliette", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Dolos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Druanga", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Aquila", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Krobelus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Neuranto", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Trostaurus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Lothar", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Styx", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Sooten", .patron=null, .primary_resource="iron-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Karura", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Magi", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Momus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Chronos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ganymede", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Gerhaift", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Heinlein", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Chrodon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ettenor", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Numrah", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Snagle", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Noventede", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Minos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Amebris", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Lath", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Haka", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Adul", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Lethe", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Furion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Alfonso", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Bandoch", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Daedelus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Acheron", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Minoa", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Angelos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tartarus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Whittier", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ethoria", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Acisrind", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Rokenharr", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Haze", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Vekars", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Kitsune", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Pentto", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Enigma", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tycho", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Aporia", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Orphne", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Gearofen", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Akasha", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Sofurna", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hermes", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Swoxter", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Manta", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Zion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Oneiros", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Nexus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Jelt", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Kratos", .patron=null, .primary_resource="iron-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Claymore", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Avakis", .patron=null, .primary_resource="coal", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Shara", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Oeris", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tresdin", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hedone", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Lilac", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tango", .patron=null, .primary_resource="crude-oil", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Dolentea", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Apate", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Warrus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Esenudreus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Joenus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Narsus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Weylop", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Warlock", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tieneo", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Znok", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Rinoto", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Azure", .patron=null, .primary_resource="crude-oil", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Zakhol", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ashura", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Krubidium", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Silverhorn", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Alecto", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Osis", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Morus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Selemaenae", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Empha", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Midas", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Akerty", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Lotuslana", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Spiriso", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Imbrium", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Quillion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Alba", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Zendia", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Linken", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Konan", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tolubai", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Magmin", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Sange", .patron=null, .primary_resource="copper-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Dionysus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Bishamonten", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Bunkle", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Memnon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Nomos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Kokytos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Crixalis", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Andragora", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ryuo", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Rivos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Constance", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Stromhurst", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Feaora", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Paquin", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Heechgata", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Mercurial", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hyperion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Xandra", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Delune", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Adalind", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Vioress", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Crean", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Alban", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Lamia", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Kaya", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Heliolyte", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tanzan", .patron=null, .primary_resource="crude-oil", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Jakiro", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Juno", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Vobis", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Corsol", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Elezar", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Lamplika", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Taras", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Atengam", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tentei", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Shellabby", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ezra", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Persephone", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Chiron", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Neevus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Rampart", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hades", .patron=null, .primary_resource="coal", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Santo", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Abyssal", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Deurus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Koskomino", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hypnos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Moirai", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Selene", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Zed", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tisiphone", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Thrasos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Beaumont", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Indarl", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Kerkon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Rhadaman", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Verbena", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Benthai", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Boros", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Aizen", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Galvania", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Prism", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Berky", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tenou", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Aeolus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Faerie", .patron=null, .primary_resource="crude-oil", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Ophion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Mobius", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Peitho", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Greenleaf", .patron=null, .primary_resource="coal", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Vesper", .patron=null, .primary_resource="crude-oil", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Rubik", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Riza", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Geive", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Palto", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Alke", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Elysium", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Eaglesong", .patron=null, .primary_resource="coal", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Daryun", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Achilles", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Brion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Grilla", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ermintrude", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Naden", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Evadome", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Amechania", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Antaeus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ender", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Demeter", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Athina", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Caerus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Witfalla", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Starfury", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Muir", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Jeroen", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ourea", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Jespur", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Jetenury", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Manelscot", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Marmo", .patron=null, .primary_resource=null, .has_biome_replacements=true, .has_tags=true },
    .{ .name="Emiir", .patron=null, .primary_resource="crude-oil", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Castor", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Petussia", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Androgun", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Chimera", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Semiele", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Lyssa", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Jetnova", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Soma", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Beylix", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Rylai", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Eulstave", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Liono", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Infernox", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Paulara", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Algea", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Gapleon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tetracat", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Alastor", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Bolina", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Penium", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Shiva", .patron=null, .primary_resource="iron-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Arturius", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Traxex", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Itnora", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Luxitania", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Taishakuten", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Bloodthorn", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Amadeo", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Plenai", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Koma", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ishmere", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Criopta", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Thalassa", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Thoon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ozwulf", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Thule", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Vietera", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Kunkri", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Aion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Kael", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ixion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Metapilla", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Mavarix", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Voxnova", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Karik", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Sturata", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Bernadette", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Legogene", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ecludies", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Abaddon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Miturion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Gorgyra", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Cinrad", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Orion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Kendapoa", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Spatha", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Indigo", .patron=null, .primary_resource="iron-ore", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Corus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Harmonia", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Arkoth", .patron=null, .primary_resource="coal", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Bromwinkle", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Nikara", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ajax", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Kaliphos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Mordiggian", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Kuyou", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Exavier", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Zauber", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Cerberus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Manearth", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Umbra", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ranolin", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Slithice", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Cadmus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Adikia", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Perodome", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Geras", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Typhon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Termina", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Oliran", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Deadrim", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hyrean", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Gorgon", .patron=null, .primary_resource="uranium-ore", .has_biome_replacements=true, .has_tags=true },
    .{ .name="Chrothurn", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Sladeshon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Nonagaz", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Sihnon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Bombato", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Mordred", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Jiangyin", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Akkolon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Alfrind", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Sworn", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hexen", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Falconsabre", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Roma", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ganus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Aiakos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ourus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Deadwood", .patron=null, .primary_resource="coal", .has_biome_replacements=false, .has_tags=true },
    .{ .name="Windlace", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Aberdon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Kara", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Koolimon", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Rutadam", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Pandion", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Shinzo", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Anax", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hecate", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Rumba", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Zomble", .patron=null, .primary_resource=null, .has_biome_replacements=true, .has_tags=true },
    .{ .name="Atos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Throix", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Zelos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Razor", .patron=null, .primary_resource="iron-ore", .has_biome_replacements=false, .has_tags=false },
    .{ .name="Mythulu", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Katski", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Morgana", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ester", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Vares", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Balanar", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Impetus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Soteria", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Arislan", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Tintavis", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Melione", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Clotho", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Aidos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Vexo", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Sakimi", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Stijio", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Regina", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Erinyes", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Lynx", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Wyvern", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Nestor", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Noctis", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Osiris", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Ariel", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Erebos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Alessandro", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Gelos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Yasha", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Empusa", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Esluna", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Hermione", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Orpheus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Limos", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Karas", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Nissaria", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Harmonette", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Piccard", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Redril", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Avernus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=true },
    .{ .name="Infamani", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Perseus", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Loliento", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Elpis", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Tyche", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Whinstone", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Budkai", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Phanto", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Toucan", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
    .{ .name="Demios", .patron=null, .primary_resource=null, .has_biome_replacements=false, .has_tags=false },
};

pub const haven_moons_names = [_][]const u8{
    "Greyhaven",
    "Solsolace",
    "Respitia",
    "Dusku",
    "Sanctunimo",
    "Gradshiem",
    "Ismet",
    "Meditato",
    "Remedy",
    "Curaga",
    "Medjed",
    "Aesseilia",
    "Seren",
    "Serapis",
    "Eshu",
    "Molli",
    "Veles",
    "Erio",
    "Arawn",
    "Cichol",
    "Donn",
    "Mannanan",
    "Morrigan",
    "Ran",
    "Culga",
    "Mantus",
    "Orcus",
    "Vanth",
    "Erebus",
    "Mors",
    "Mara",
    "Degei",
    "Pana",
};

pub const vulcanite_planets_names = [_][]const u8{
    "Aine",
    "Theros",
    "Aestas",
    "Damia",
    "Ruamati",
    "Miochin",
    "Hephaestus",
    "Ogun",
    "Shennong",
    "Agni",
    "Agneya",
    "Fuji",
    "Odqan",
    "Turgmam",
    "Alaz",
    "Kamar",
    "Grannus",
    "Mariel",
};

pub const cryonite_moons_names = [_][]const u8{
    "Shakok",
    "Vionette",
    "Snowdrop",
    "Glacier",
    "Hagen",
    "Hothier",
    "Calippo",
    "Pastille",
    "Cornetto",
    "Frost",
    "Cryonia",
    "Beira",
    "Khione",
    "Marzanna",
    "Morozko",
    "Boreas",
};

pub const iridium_moons_names = [_][]const u8{
    "Kothar",
    "Ptah",
    "Goibniu",
    "Anvil",
    "Sethlans",
    "Svarog",
    "Gibil",
    "Fornax",
    "Forgehammer",
    "Wayland",
    "Ilmarinen",
    "Lugh",
    "Seker",
    "Cyclops",
    "Hadur",
    "Ikenga",
};

pub const holmium_moons_names = [_][]const u8{
    "Enlil",
    "Amun",
    "Henkhisesui",
    "Shu",
    "Ninlil",
    "Holmera",
    "Pazu",
    "Tazer",
    "Verbti",
    "Shurdhi",
    "Varpulis",
    "Egoi",
    "Borroum",
    "Sidhe",
    "Njord",
    "Kari",
};

pub const vitamelange_moons_names = [_][]const u8{
    "Freyr",
    "Bigrid",
    "Eostre",
    "Daisy",
    "Ver",
    "Jura",
    "Buttercup",
    "Eiar",
    "Morityema",
    "Gardinia",
    "Shire",
    "Mossgarden",
    "Fern",
    "Lilly",
    "Rose",
    "Tulip",
    "Everglade",
};
