FROM factoriotools/factorio:stable
COPY saves/calib-10003.zip /factorio/saves/
COPY mods/ /factorio/mods/
COPY config/ /factorio/config/
COPY script-output/ /factorio/script-output/
ENV LOAD_LATEST_SAVE=false
ENV SAVE_NAME=calib-10003
