#!/usr/bin/env python3
"""Generate the sa-probe mod: registers noise-expressions that wrap the engine
voronoi_* / terrace natives with fixed params, so map-gen-settings can name
them and calculate_tile_properties can evaluate them (only registered names
are accepted). Also writes the per-run map-gen-settings.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
MODS = os.path.join(HERE, "mods", "sa-probe")
os.makedirs(os.path.join(MODS, "data"), exist_ok=True)

# expr spec: (out, grid, jitter, dist, seed1expr, tag) -> name suffix
# out: cid/spot/facet/pyr
def vexpr(out, grid, jitter, dist, seed1, tag):
    name = f"vp_{tag}_{out}"
    args = (f"x = x, y = y, seed0 = map_seed, seed1 = {seed1}, "
            f"grid_size = {grid}, distance_type = '{dist}', jitter = {jitter}")
    fn = {"cid": "voronoi_cell_id", "spot": "voronoi_spot_noise",
          "facet": "voronoi_facet_noise", "pyr": "voronoi_pyramid_noise"}[out]
    return {"type": "noise-expression", "name": name, "expression": f"{fn}{{{args}}}"}

def texpr(tag, value, offset, width, strength):
    name = f"vp_{tag}"
    return {"type": "noise-expression", "name": name,
            "expression": f"terrace{{value = {value}, offset = {offset}, width = {width}, strength = {strength}}}"}

exprs = []
# (grid, jitter, dist, seed1 as lua literal)
matrix = [
    (32, 0.0, "euclidean", "42",  "a"),
    (32, 0.5, "euclidean", "42",  "b"),
    (32, 1.0, "euclidean", "42",  "c"),
    (24, 0.25, "manhattan", "42", "d"),
    (24, 0.5, "chebyshev", "42",  "e"),
    (16, 0.5, "minkowski3", "42", "f"),
    (32, 0.5, "euclidean", "'hxprobe'", "g"),
    (10, 0.5, "euclidean", "'aquilo-cracks'", "h"),
    (64, 0.35, "manhattan", "'fulgora_cells'", "i"),
]
outs_per = {"a": ["cid", "spot", "facet", "pyr"], "b": ["cid", "spot", "facet", "pyr"],
            "c": ["cid", "spot", "facet"], "d": ["cid", "facet", "spot"],
            "e": ["cid", "facet", "spot"], "f": ["cid", "facet", "spot"],
            "g": ["cid", "spot"], "h": ["cid", "facet"], "i": ["cid", "facet"]}
for grid, jitter, dist, seed1, tag in matrix:
    for out in outs_per[tag]:
        if out == "pyr" and dist == "minkowski3":
            continue
        exprs.append(vexpr(out, grid, jitter, dist, seed1, tag))
# terraces (gleba-style + identity/edge cases)
exprs.append(texpr("t_gleba", "min(150, -25 + 0.3 * x * 100)", 40, 20, 0.2))
exprs.append(texpr("t_v1", "v", 0, 1, 0.0))
exprs.append(texpr("t_v2", "x * 1.0 - 500", 40, 20, 0.5))

# split into runs of <=6 slots over the 6 engine property names
slots = ["aux", "moisture", "temperature", "elevation", "cliffiness", "cliff_elevation"]
runs = []
cur = []
for e in exprs:
    if len(cur) == 6:
        runs.append(cur); cur = []
    cur.append(e)
if cur: runs.append(cur)

with open(os.path.join(MODS, "info.json"), "w") as f:
    json.dump({"name": "sa-probe", "version": "0.0.1", "title": "sa-probe",
               "author": "seedsearch", "factorio_version": "2.0",
               "dependencies": ["base >= 2.0"]}, f)

with open(os.path.join(MODS, "data.lua"), "w") as f:
    f.write('-- generated by gen_probe_mod.py\n')
    f.write('data:extend({\n')
    for e in exprs:
        f.write('  {type = "noise-expression", name = "%s", expression = %s},\n'
                % (e["name"], json.dumps(e["expression"])))
    f.write('})\n')

with open(os.path.join(HERE, "out", "probe-runs.json"), "w") as f:
    json.dump({"slots": slots, "runs": [[e["name"] for e in r] for r in runs]}, f, indent=1)

print(f"mod with {len(exprs)} expressions, {len(runs)} runs of <=6")
for i, r in enumerate(runs):
    print(" run", i, r)
